import React, { Component } from "react";
import './css/vstyles.css'

class Report extends Component{
    render(){
        return(
            <div style={{
                padding:'13.92%',
                height:'50%',
                background: `url(https://wallpaperaccess.com/full/1267583.jpg)`,
                backgroundRepeat: `no-repeat`,
                backgroundSize: `center`}}>  <h2 style={{fontFamily:"Times New Roman", Times: 'serif',  fontWeight: 'bold',  textAlign: 'center' , marginTop:'20px'}}>Overview of the Porject </h2> <br></br><p   style={{textAlign: 'justify',fontFamily:"Times New Roman", fontStyle: 'oblique', fontSize:'20px' ,Times: 'serif' , fontWeight: '20px' ,color:'  #595959'}} >   In This digital world, Everything is Digitalized but Still, Some Practices are a bit unvarying, One of those is the certificate verification process. The foremost important documents are certificates for graduates from universities and other educational institutions. However, it is costly and time-consuming to check certificates using traditional methods. This paper aims to introduce a theoretical model, which can give the possible infusion for the issue and verification process of academic certificates using blockchain technology. there are so many advantages of blockchain apart from finance, one of them is a supply chain. In this model, we are using blockchain and distributed storage. There are many functions such as hash, public and private key cryptography, digital signatures, peer-to-peer networks and work evidence in blockchain technology. In This model, we are using IPFS for distributed storage (peer-to-peer) everything in ipfs is publicly available with the appropriate hash generated by ipfs, for this reason, We added  Client-side encryption as Securrity Layer. To secure the documents uploaded by the Issuer. The models formulate a system divided into two principal processes using different elements, namely the issuance of a digital certificate of academic signature and the academic certificate verification.
                </p></div>
        );
    }
}

export default Report;